Use new --user-config option
[SVN r36455]

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -282,21 +282,21 @@ else
 fi
 
 # Backup the user's existing user-config.jam
-JAM_CONFIG_OUT="$HOME/user-config.jam"
-if test -r "$HOME/user-config.jam"; then
+JAM_CONFIG_OUT="user-config.jam"
+if test -r "user-config.jam"; then
   counter=1
  
-  while test -r "$HOME/user-config.jam.$counter"; do
+  while test -r "user-config.jam.$counter"; do
     counter=`expr $counter + 1`
   done
 
-  echo "Backing up existing Boost.Build configuration in $HOME/user-config.jam.$counter"
-  mv "$HOME/user-config.jam" "$HOME/user-config.jam.$counter"
+  echo "Backing up existing Boost.Build configuration in user-config.jam.$counter"
+  mv "user-config.jam" "user-config.jam.$counter"
 fi
 
 # Generate user-config.jam
-echo "Generating Boost.Build configuration in $HOME/user-config.jam..."
-cat > $HOME/user-config.jam <<EOF
+echo "Generating Boost.Build configuration in user-config.jam..."
+cat > user-config.jam <<EOF
 # Boost.Build Configuration
 # Automatically generated by Boost configure 
 
@@ -306,7 +306,7 @@ EOF
 
 #  - Python configuration
 if test "x$flag_no_python" = x; then
-  cat >> $HOME/user-config.jam <<EOF
+  cat >> user-config.jam <<EOF
 
 # Python configuration
 using python : $PYTHON_VERSION : $PYTHON_ROOT ;
@@ -325,8 +325,8 @@ INCLUDEDIR=$INCLUDEDIR
 LIBS=$LIBS
 
 all: .dummy
-	@echo "\$(BJAM) \$(BJAM_CONFIG) \$(LIBS)"
-	@\$(BJAM) \$(BJAM_CONFIG) \$(LIBS) || \\
+	@echo "\$(BJAM) \$(BJAM_CONFIG) --user-config=user-config.jam \$(LIBS)"
+	@\$(BJAM) \$(BJAM_CONFIG) --user-config=user-config.jam \$(LIBS) || \\
 	echo "Not all Boost libraries built properly."
 
 clean: .dummy
@@ -336,11 +336,11 @@ distclean: clean
 	rm -rf Makefile config.log
 
 check: .dummy
-	@cd status && ../\$(BJAM) \$(BJAM_CONFIG) test || echo "Some Boost regression tests failed. This is normal."
+	@cd status && ../\$(BJAM) \$(BJAM_CONFIG) --user-config=user-config.jam test || echo "Some Boost regression tests failed. This is normal."
 
 install: .dummy
-	@echo "\$(BJAM) \$(BJAM_CONFIG) --prefix=\$(PREFIX) --exec-prefix=\$(EPREFIX) --libdir=\$(LIBDIR) --includedir=\$(INCLUDEDIR) \$(LIBS) install"
-	@\$(BJAM) \$(BJAM_CONFIG) --prefix=\$(PREFIX) --exec-prefix=\$(EPREFIX) --libdir=\$(LIBDIR) --includedir=\$(INCLUDEDIR) \$(LIBS) install || echo "Not all Boost libraries built properly."
+	@echo "\$(BJAM) \$(BJAM_CONFIG) --user-config=user-config.jam --prefix=\$(PREFIX) --exec-prefix=\$(EPREFIX) --libdir=\$(LIBDIR) --includedir=\$(INCLUDEDIR) \$(LIBS) install"
+	@\$(BJAM) \$(BJAM_CONFIG) --user-config=user-config.jam --prefix=\$(PREFIX) --exec-prefix=\$(EPREFIX) --libdir=\$(LIBDIR) --includedir=\$(INCLUDEDIR) \$(LIBS) install || echo "Not all Boost libraries built properly."
 
 .dummy:
 
